name: Log Push to Central Repo

on: [push]

jobs:
  log_push:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest commit info
        id: vars
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY}" >> $GITHUB_ENV
          echo "DATE=$(date -u +"%Y-%m-%d %H:%M UTC")" >> $GITHUB_ENV
          echo "COMMIT_SHA=${GITHUB_SHA}" >> $GITHUB_ENV
          echo "COMMIT_URL=https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}" >> $GITHUB_ENV
          export VAULT_ADDR="http://127.0.0.1:8200"

      - name: Get PUSH_TOKEN from Vault
        run: |
          PUSH_TOKEN=$(vault kv get -mount=secret -field=PUSH_TOKEN logger)
          echo "PUSH_TOKEN=$PUSH_TOKEN" >> $GITHUB_ENV

      - name: Log to central repo
        run: |
          git config --global user.name "GitHub Logger"
          git config --global user.email "logger@example.com"
          
          # Get commit message from current repo
          COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s" $COMMIT_SHA || echo "No message")

          # Create log entry content
          LOG_ENTRY="| $DATE | $REPO_NAME | [${COMMIT_SHA:0:7}]($COMMIT_URL) | $COMMIT_MESSAGE |"

          # Push directly to central repo using GitHub API
          curl -X PUT \
            -H "Authorization: token $PUSH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{
              \"message\": \"Log push from $REPO_NAME\",
              \"content\": \"$(echo "$LOG_ENTRY" | base64 -w 0)\"
            }" \
            https://api.github.com/repos/knguyennt/projects-history-logs/contents/log.md
