name: Log Push to Central Repo

on: [push]

jobs:
  log_push:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest commit info
        id: vars
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY}" >> $GITHUB_ENV
          echo "DATE=$(date -u +"%Y-%m-%d %H:%M UTC")" >> $GITHUB_ENV
          echo "COMMIT_SHA=${GITHUB_SHA}" >> $GITHUB_ENV
          echo "COMMIT_URL=https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Clone central logging repo
        run: |
          git config --global user.name "GitHub Logger"
          git config --global user.email "logger@example.com"
          git clone https://x-access-token:${{ secrets.PUSH_TOKEN }}@github.com/knguyennt/projects-history-logs.git
          cd projects-history-logs

          # Get commit message
          COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s" $COMMIT_SHA || echo "No message")

          # Ensure log.md exists and has header
          if [ ! -f log.md ]; then
            echo "# Project Push History Log" > log.md
            echo "" >> log.md
            echo "| DATE | REPO | COMMIT | MESSAGE |" >> log.md
            echo "|------|------|--------|---------|" >> log.md
          fi

          # Add log entry
          echo "| $DATE | $REPO_NAME | [${COMMIT_SHA:0:7}]($COMMIT_URL) | $COMMIT_MESSAGE |" >> log.md

          # Commit & push
          git add log.md
          git commit -m "Log push from $REPO_NAME"
          git push
